/* eslint-disable */
// Otomatik üretilir — npm run catalog-all-theme-videos

export type ThemeSubject = 'math' | 'turkce' | 'fen' | 'hayat' | 'english';

export const ALL_THEME_VIDEO_SOURCES: Record<string, number> = {
  'math-tema-1': require('../../assets/videos/math/Math_Tema1.mp4'),
  'math-tema-2': require('../../assets/videos/math/Math_Tema2.mp4'),
  'math-tema-3': require('../../assets/videos/math/Math_Tema3.mp4'),
  'math-tema-4': require('../../assets/videos/math/Math_Tema4.mp4'),
  'math-tema-5': require('../../assets/videos/math/Math_Tema5.mp4'),
  'math-tema-6': require('../../assets/videos/math/Math_Tema6.mp4'),
  'math-tema-7': require('../../assets/videos/math/Math_Tema7.mp4'),
  'math-tema-8': require('../../assets/videos/math/Math_Tema8.mp4'),
  'math-tema-9': require('../../assets/videos/math/Math_Tema9.mp4'),
  'math-tema-10': require('../../assets/videos/math/Math_Tema10.mp4'),
  'turkce-tema-1': require('../../assets/videos/turkce/Turk_Tema1.mp4'),
  'turkce-tema-2': require('../../assets/videos/turkce/Turk_Tema2.mp4'),
  'turkce-tema-3': require('../../assets/videos/turkce/Turk_Tema3.mp4'),
  'turkce-tema-4': require('../../assets/videos/turkce/Turk_Tema4.mp4'),
  'turkce-tema-5': require('../../assets/videos/turkce/Turk_Tema5.mp4'),
  'turkce-tema-6': require('../../assets/videos/turkce/Turk_Tema6.mp4'),
  'turkce-tema-7': require('../../assets/videos/turkce/Turk_Tema7.mp4'),
  'turkce-tema-8': require('../../assets/videos/turkce/Turk_Tema8.mp4'),
  'turkce-tema-9': require('../../assets/videos/turkce/Turk_Tema9.mp4'),
  'turkce-tema-10': require('../../assets/videos/turkce/Turk_Tema10.mp4'),
  'fen-tema-1': require('../../assets/videos/fen/Fen_Tema1.mp4'),
  'fen-tema-2': require('../../assets/videos/fen/Fen_Tema2.mp4'),
  'fen-tema-3': require('../../assets/videos/fen/Fen_Tema3.mp4'),
  'fen-tema-4': require('../../assets/videos/fen/Fen_Tema4.mp4'),
  'fen-tema-5': require('../../assets/videos/fen/Fen_Tema5.mp4'),
  'fen-tema-6': require('../../assets/videos/fen/Fen_Tema6.mp4'),
  'fen-tema-7': require('../../assets/videos/fen/Fen_Tema7.mp4'),
  'fen-tema-8': require('../../assets/videos/fen/Fen_Tema8.mp4'),
  'fen-tema-9': require('../../assets/videos/fen/Fen_Tema9.mp4'),
  'fen-tema-10': require('../../assets/videos/fen/Fen_Tema10.mp4'),
  'hayat-tema-1': require('../../assets/videos/hayat/Hayat_Tema1.mp4'),
  'hayat-tema-2': require('../../assets/videos/hayat/Hayat_Tema2.mp4'),
  'hayat-tema-3': require('../../assets/videos/hayat/Hayat_Tema3.mp4'),
  'hayat-tema-4': require('../../assets/videos/hayat/Hayat_Tema4.mp4'),
  'hayat-tema-5': require('../../assets/videos/hayat/Hayat_Tema5.mp4'),
  'hayat-tema-6': require('../../assets/videos/hayat/Hayat_Tema6.mp4'),
  'hayat-tema-7': require('../../assets/videos/hayat/Hayat_Tema7.mp4'),
  'hayat-tema-8': require('../../assets/videos/hayat/Hayat_Tema8.mp4'),
  'hayat-tema-9': require('../../assets/videos/hayat/Hayat_Tema9.mp4'),
  'hayat-tema-10': require('../../assets/videos/hayat/Hayat_Tema10.mp4'),
  'english-tema-1': require('../../assets/videos/english/Eng_Tema1.mp4'),
  'english-tema-2': require('../../assets/videos/english/Eng_Tema2.mp4'),
  'english-tema-3': require('../../assets/videos/english/Eng_Tema3.mp4'),
  'english-tema-4': require('../../assets/videos/english/Eng_Tema4.mp4'),
  'english-tema-5': require('../../assets/videos/english/Eng_Tema5.mp4'),
  'english-tema-6': require('../../assets/videos/english/Eng_Tema6.mp4'),
  'english-tema-7': require('../../assets/videos/english/Eng_Tema7.mp4'),
  'english-tema-8': require('../../assets/videos/english/Eng_Tema8.mp4'),
};

export const ALL_THEME_VIDEO_COUNT = 48;
