/* eslint-disable */
// Otomatik üretilir — tüm temalar için video mapping

export const ALL_THEME_VIDEO_SOURCES: Record<string, number> = {
  'math-tema1': require('../../assets/videos/math/Math_Tema1.mp4'),
  'math-tema2': require('../../assets/videos/math/Math_Tema2.mp4'),
  'math-tema3': require('../../assets/videos/math/Math_Tema3.mp4'),
  'math-tema4': require('../../assets/videos/math/Math_Tema4.mp4'),
  'math-tema5': require('../../assets/videos/math/Math_Tema5.mp4'),
  'math-tema6': require('../../assets/videos/math/Math_Tema6.mp4'),
  'math-tema7': require('../../assets/videos/math/Math_Tema7.mp4'),
  'math-tema8': require('../../assets/videos/math/Math_Tema8.mp4'),
  'math-tema9': require('../../assets/videos/math/Math_Tema9.mp4'),
  'math-tema10': require('../../assets/videos/math/Math_Tema10.mp4'),
  'turkce-tema1': require('../../assets/videos/turkce/Turk_Tema1.mp4'),
  'turkce-tema2': require('../../assets/videos/turkce/Turk_Tema2.mp4'),
  'turkce-tema3': require('../../assets/videos/turkce/Turk_Tema3.mp4'),
  'turkce-tema4': require('../../assets/videos/turkce/Turk_Tema4.mp4'),
  'turkce-tema5': require('../../assets/videos/turkce/Turk_Tema5.mp4'),
  'turkce-tema6': require('../../assets/videos/turkce/Turk_Tema6.mp4'),
  'turkce-tema7': require('../../assets/videos/turkce/Turk_Tema7.mp4'),
  'turkce-tema8': require('../../assets/videos/turkce/Turk_Tema8.mp4'),
  'turkce-tema9': require('../../assets/videos/turkce/Turk_Tema9.mp4'),
  'turkce-tema10': require('../../assets/videos/turkce/Turk_Tema10.mp4'),
  'fen-tema1': require('../../assets/videos/fen/Fen_Tema1.mp4'),
  'fen-tema2': require('../../assets/videos/fen/Fen_Tema2.mp4'),
  'fen-tema3': require('../../assets/videos/fen/Fen_Tema3.mp4'),
  'fen-tema4': require('../../assets/videos/fen/Fen_Tema4.mp4'),
  'fen-tema5': require('../../assets/videos/fen/Fen_Tema5.mp4'),
  'fen-tema6': require('../../assets/videos/fen/Fen_Tema6.mp4'),
  'fen-tema7': require('../../assets/videos/fen/Fen_Tema7.mp4'),
  'fen-tema8': require('../../assets/videos/fen/Fen_Tema8.mp4'),
  'fen-tema9': require('../../assets/videos/fen/Fen_Tema9.mp4'),
  'fen-tema10': require('../../assets/videos/fen/Fen_Tema10.mp4'),
  'hayat-tema1': require('../../assets/videos/hayat/Hayat_Tema1.mp4'),
  'hayat-tema2': require('../../assets/videos/hayat/Hayat_Tema2.mp4'),
  'hayat-tema3': require('../../assets/videos/hayat/Hayat_Tema3.mp4'),
  'hayat-tema4': require('../../assets/videos/hayat/Hayat_Tema4.mp4'),
  'hayat-tema5': require('../../assets/videos/hayat/Hayat_Tema5.mp4'),
  'hayat-tema6': require('../../assets/videos/hayat/Hayat_Tema6.mp4'),
  'hayat-tema7': require('../../assets/videos/hayat/Hayat_Tema7.mp4'),
  'hayat-tema8': require('../../assets/videos/hayat/Hayat_Tema8.mp4'),
  'hayat-tema9': require('../../assets/videos/hayat/Hayat_Tema9.mp4'),
  'hayat-tema10': require('../../assets/videos/hayat/Hayat_Tema10.mp4'),
  'english-tema1': require('../../assets/videos/english/Eng_Tema1.mp4'),
  'english-tema2': require('../../assets/videos/english/Eng_Tema2.mp4'),
  'english-tema3': require('../../assets/videos/english/Eng_Tema3.mp4'),
  'english-tema4': require('../../assets/videos/english/Eng_Tema4.mp4'),
  'english-tema5': require('../../assets/videos/english/Eng_Tema5.mp4'),
  'english-tema6': require('../../assets/videos/english/Eng_Tema6.mp4'),
  'english-tema7': require('../../assets/videos/english/Eng_Tema7.mp4'),
  'english-tema8': require('../../assets/videos/english/Eng_Tema8.mp4'),
};

export const ALL_THEME_VIDEO_COUNT = 48;